source "https://rubygems.org"

gem "jekyll", "~> 3.9"
gem "minimal-mistakes-jekyll"
gem "bibtex-ruby", "4.4.6"
gem "jekyll-sitemap"
gem "jekyll-coffeescript"
gem "kramdown-parser-gfm"
gem "octopress", "~> 3.0.0.rc.12"
gem "webrick", "~> 1.8"
